# pyproject.toml
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests2",
    "integration",
]
[tool.flake8.ini_options]
minversion = "6.0"
[tool.flake8]
minversion = "6.0"
